/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export type ShiftCoHost = string;
export interface UniversityBoardCard {
    id: CardId;
    col: Col;
    title: Title;
    createdAt: CreatedAt;
    createdBy: CreatedBy;
    term: Term;
    week: string;
    dueDate: string;
    course: string;
    assignmentTitle: string;
}
export type ShiftPattern = string;
export type Col = string;
export type Term = string;
export type Title = string;
export type CreatedBy = string;
export type CreatedAt = string;
export interface StaffingBoardCard {
    id: CardId;
    col: Col;
    status: Status;
    shiftCoHost: ShiftCoHost;
    createdAt: CreatedAt;
    createdBy: CreatedBy;
    personName: PersonName;
    login: Login;
    shiftPattern: ShiftPattern;
}
export type Status = string;
export type PersonName = string;
export type Login = string;
export type CardId = Uint8Array;
export interface backendInterface {
    getAllStaffingCards(): Promise<Array<StaffingBoardCard>>;
    getAllUniversityCards(): Promise<Array<UniversityBoardCard>>;
    getLastUpdated(): Promise<string>;
    saveAllStaffingCards(cards: Array<StaffingBoardCard>): Promise<void>;
    saveAllUniversityCards(cards: Array<UniversityBoardCard>): Promise<void>;
    setLastUpdated(timestamp: string): Promise<void>;
}
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async getAllStaffingCards(): Promise<Array<StaffingBoardCard>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllStaffingCards();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllStaffingCards();
            return result;
        }
    }
    async getAllUniversityCards(): Promise<Array<UniversityBoardCard>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllUniversityCards();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllUniversityCards();
            return result;
        }
    }
    async getLastUpdated(): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.getLastUpdated();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLastUpdated();
            return result;
        }
    }
    async saveAllStaffingCards(arg0: Array<StaffingBoardCard>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveAllStaffingCards(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveAllStaffingCards(arg0);
            return result;
        }
    }
    async saveAllUniversityCards(arg0: Array<UniversityBoardCard>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveAllUniversityCards(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveAllUniversityCards(arg0);
            return result;
        }
    }
    async setLastUpdated(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setLastUpdated(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setLastUpdated(arg0);
            return result;
        }
    }
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
